In [1]:
import json
import csv
import os

# 当前目录
current_dir = os.getcwd()

# 输入和输出文件名
input_file = "knowledges (1).json"   # 修改为你的 JSON 文件名
output_file = "knowledges.tsv"

# 你要保留的字段
fieldnames = [
    'relation_type',
    'source_name',
    'source_type',
    'source_id',
    'target_name',
    'target_type',
    'target_id',
    'key_sentence',
    'pmid'
]

# 读取 JSON
file_path = os.path.join(current_dir, input_file)
with open(file_path, 'r', encoding='utf-8') as f:
    items = json.load(f)

# 转换数据
data = []
for item in items:
    row = {k: item.get(k, '') for k in fieldnames}
    data.append(row)
    
# 写入 TSV
output_path = os.path.join(current_dir, output_file)
with open(output_path, 'w', encoding='utf-8', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter='\t')
    writer.writeheader()
    writer.writerows(data)

print(f"✅ 合并完成，共写入 {len(data)} 条记录")
print(f"📄 文件已保存到: {output_path}")

✅ 合并完成，共写入 5622 条记录
📄 文件已保存到: /Users/zhuzhixing/KG/biomedgps-data/graph_data/relations/customdb/20260213版/knowledges.tsv

In [3]:
import pandas as pd

# 读取转换后的 formatted 知识图谱文件
formatted_dfv20260213 = pd.read_csv("knowledges.tsv", sep="\t")

In [4]:
formatted_dfv20260213

,relation_type,source_name,source_type,source_id,target_name,target_type,target_id,key_sentence,pmid
0,BioMedGPS::E+::Disease:Gene,BDNF,Gene,ENTREZ:627,CFS,Disease,MONDO:0005404,"Compared to controls, serum BNDF was higher in...",NaN
1,BioMedGPS::Treatment::Compound:Disease,influenza,Disease,MONDO:0005812,PEA,Compound,DrugBank:DB10551,PEA is an interesting anti-inflammatory therap...,NaN
2,BioMedGPS::Treatment::Compound:Disease,common cold,Disease,MONDO:0005709,PEA,Compound,DrugBank:DB10551,PEA is an interesting anti-inflammatory therap...,NaN
3,BioMedGPS::Target::Gene:Disease,NSCLC,Disease,MONDO:0005233,ROS1,Gene,ENTREZ:6098,ROS1 gene fusions are an established oncogenic...,NaN
4,BioMedGPS::SimilarWith::Disease:Disease,PTSD,Disease,MONDO:0005146,major depressive disorder,Disease,MONDO:0002009,Our data suggest shared and distinct molecular...,NaN
...,...,...,...,...,...,...,...,...,...
5617,BioMedGPS::InPathway::Gene:Pathway,TFEB (transcription factor EB),Gene,ENTREZ:21425,macroautophagy/autophagy,Pathway,REACT:R-MMU-1632852,A CRISPR-Cas9-engineered ANXA2E139A mutation i...,NaN
5618,BioMedGPS::Causer::Gene:Disease,TFEB (transcription factor EB),Gene,ENTREZ:21425,pulmonary fibrosis,Disease,MONDO:0002771,"Notably, we observe lowered TFEB and LC3B leve...",NaN
5619,BioMedGPS::E-::Disease:Gene,pulmonary fibrosis,Disease,MONDO:0002771,LC3B,Gene,ENTREZ:67443,"Notably, we observe lowered TFEB and LC3B leve...",NaN
5620,BioMedGPS::AssociatedWith::Pathway:Disease,macroautophagy/autophagy,Pathway,REACT:R-MMU-1632852,pulmonary fibrosis,Disease,MONDO:0002771,"Notably, we observe lowered TFEB and LC3B leve...",NaN
5621,BioMedGPS::Target::Gene:Disease,anxa2,Gene,ENTREZ:12306,pulmonary fibrosis,Disease,MONDO:0002771,"Collectively, our data demonstrate that ANXA2 ...",NaN

In [5]:
# 统一两表的列结构
formatted_dfv20260213["resource"] = "CustomDB"
formatted_dfv20260213["formatted_relation_type"] = formatted_dfv20260213["relation_type"]  # 或留空
formatted_dfv20260213["raw_source_id"] = formatted_dfv20260213["source_id"]
formatted_dfv20260213["raw_target_id"] = formatted_dfv20260213["target_id"]
formatted_dfv20260213["raw_source_type"] = formatted_dfv20260213["source_type"]
formatted_dfv20260213["raw_target_type"] = formatted_dfv20260213["source_type"]
formatted_dfv20260213["pmids"] = formatted_dfv20260213["pmid"]  # 字段名对齐
formatted_dfv20260213 = formatted_dfv20260213.drop(columns=["pmid", "source_name", "target_name"], errors="ignore")
formatted_dfv20260213

,relation_type,source_type,source_id,target_type,target_id,key_sentence,resource,formatted_relation_type,raw_source_id,raw_target_id,raw_source_type,raw_target_type,pmids
0,BioMedGPS::E+::Disease:Gene,Gene,ENTREZ:627,Disease,MONDO:0005404,"Compared to controls, serum BNDF was higher in...",CustomDB,BioMedGPS::E+::Disease:Gene,ENTREZ:627,MONDO:0005404,Gene,Gene,NaN
1,BioMedGPS::Treatment::Compound:Disease,Disease,MONDO:0005812,Compound,DrugBank:DB10551,PEA is an interesting anti-inflammatory therap...,CustomDB,BioMedGPS::Treatment::Compound:Disease,MONDO:0005812,DrugBank:DB10551,Disease,Disease,NaN
2,BioMedGPS::Treatment::Compound:Disease,Disease,MONDO:0005709,Compound,DrugBank:DB10551,PEA is an interesting anti-inflammatory therap...,CustomDB,BioMedGPS::Treatment::Compound:Disease,MONDO:0005709,DrugBank:DB10551,Disease,Disease,NaN
3,BioMedGPS::Target::Gene:Disease,Disease,MONDO:0005233,Gene,ENTREZ:6098,ROS1 gene fusions are an established oncogenic...,CustomDB,BioMedGPS::Target::Gene:Disease,MONDO:0005233,ENTREZ:6098,Disease,Disease,NaN
4,BioMedGPS::SimilarWith::Disease:Disease,Disease,MONDO:0005146,Disease,MONDO:0002009,Our data suggest shared and distinct molecular...,CustomDB,BioMedGPS::SimilarWith::Disease:Disease,MONDO:0005146,MONDO:0002009,Disease,Disease,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5617,BioMedGPS::InPathway::Gene:Pathway,Gene,ENTREZ:21425,Pathway,REACT:R-MMU-1632852,A CRISPR-Cas9-engineered ANXA2E139A mutation i...,CustomDB,BioMedGPS::InPathway::Gene:Pathway,ENTREZ:21425,REACT:R-MMU-1632852,Gene,Gene,NaN
5618,BioMedGPS::Causer::Gene:Disease,Gene,ENTREZ:21425,Disease,MONDO:0002771,"Notably, we observe lowered TFEB and LC3B leve...",CustomDB,BioMedGPS::Causer::Gene:Disease,ENTREZ:21425,MONDO:0002771,Gene,Gene,NaN
5619,BioMedGPS::E-::Disease:Gene,Disease,MONDO:0002771,Gene,ENTREZ:67443,"Notably, we observe lowered TFEB and LC3B leve...",CustomDB,BioMedGPS::E-::Disease:Gene,MONDO:0002771,ENTREZ:67443,Disease,Disease,NaN
5620,BioMedGPS::AssociatedWith::Pathway:Disease,Pathway,REACT:R-MMU-1632852,Disease,MONDO:0002771,"Notably, we observe lowered TFEB and LC3B leve...",CustomDB,BioMedGPS::AssociatedWith::Pathway:Disease,REACT:R-MMU-1632852,MONDO:0002771,Pathway,Pathway,NaN
5621,BioMedGPS::Target::Gene:Disease,Gene,ENTREZ:12306,Disease,MONDO:0002771,"Collectively, our data demonstrate that ANXA2 ...",CustomDB,BioMedGPS::Target::Gene:Disease,ENTREZ:12306,MONDO:0002771,Gene,Gene,NaN

In [6]:
# 1. 读取 formatted_customdb.tsv 文件，获取列顺序参考
formatted_ref = pd.read_csv("/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb/formatted_customdb.tsv", sep="\t", nrows=1)
expected_columns = list(formatted_ref.columns)
expected_columns

['raw_source_id',
 'raw_target_id',
 'raw_source_type',
 'raw_target_type',
 'relation_type',
 'resource',
 'pmids',
 'key_sentence',
 'source_id',
 'source_type',
 'target_id',
 'target_type',
 'formatted_relation_type']

In [7]:
# 2. 对 formatted_dfv20250926 进行重排
formatted_dfv20260213 = formatted_dfv20260213.reindex(columns=expected_columns)
formatted_dfv20260213

,raw_source_id,raw_target_id,raw_source_type,raw_target_type,relation_type,resource,pmids,key_sentence,source_id,source_type,target_id,target_type,formatted_relation_type
0,ENTREZ:627,MONDO:0005404,Gene,Gene,BioMedGPS::E+::Disease:Gene,CustomDB,NaN,"Compared to controls, serum BNDF was higher in...",ENTREZ:627,Gene,MONDO:0005404,Disease,BioMedGPS::E+::Disease:Gene
1,MONDO:0005812,DrugBank:DB10551,Disease,Disease,BioMedGPS::Treatment::Compound:Disease,CustomDB,NaN,PEA is an interesting anti-inflammatory therap...,MONDO:0005812,Disease,DrugBank:DB10551,Compound,BioMedGPS::Treatment::Compound:Disease
2,MONDO:0005709,DrugBank:DB10551,Disease,Disease,BioMedGPS::Treatment::Compound:Disease,CustomDB,NaN,PEA is an interesting anti-inflammatory therap...,MONDO:0005709,Disease,DrugBank:DB10551,Compound,BioMedGPS::Treatment::Compound:Disease
3,MONDO:0005233,ENTREZ:6098,Disease,Disease,BioMedGPS::Target::Gene:Disease,CustomDB,NaN,ROS1 gene fusions are an established oncogenic...,MONDO:0005233,Disease,ENTREZ:6098,Gene,BioMedGPS::Target::Gene:Disease
4,MONDO:0005146,MONDO:0002009,Disease,Disease,BioMedGPS::SimilarWith::Disease:Disease,CustomDB,NaN,Our data suggest shared and distinct molecular...,MONDO:0005146,Disease,MONDO:0002009,Disease,BioMedGPS::SimilarWith::Disease:Disease
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5617,ENTREZ:21425,REACT:R-MMU-1632852,Gene,Gene,BioMedGPS::InPathway::Gene:Pathway,CustomDB,NaN,A CRISPR-Cas9-engineered ANXA2E139A mutation i...,ENTREZ:21425,Gene,REACT:R-MMU-1632852,Pathway,BioMedGPS::InPathway::Gene:Pathway
5618,ENTREZ:21425,MONDO:0002771,Gene,Gene,BioMedGPS::Causer::Gene:Disease,CustomDB,NaN,"Notably, we observe lowered TFEB and LC3B leve...",ENTREZ:21425,Gene,MONDO:0002771,Disease,BioMedGPS::Causer::Gene:Disease
5619,MONDO:0002771,ENTREZ:67443,Disease,Disease,BioMedGPS::E-::Disease:Gene,CustomDB,NaN,"Notably, we observe lowered TFEB and LC3B leve...",MONDO:0002771,Disease,ENTREZ:67443,Gene,BioMedGPS::E-::Disease:Gene
5620,REACT:R-MMU-1632852,MONDO:0002771,Pathway,Pathway,BioMedGPS::AssociatedWith::Pathway:Disease,CustomDB,NaN,"Notably, we observe lowered TFEB and LC3B leve...",REACT:R-MMU-1632852,Pathway,MONDO:0002771,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
5621,ENTREZ:12306,MONDO:0002771,Gene,Gene,BioMedGPS::Target::Gene:Disease,CustomDB,NaN,"Collectively, our data demonstrate that ANXA2 ...",ENTREZ:12306,Gene,MONDO:0002771,Disease,BioMedGPS::Target::Gene:Disease

In [8]:
import pandas as pd

# 1. 读取两个文件
formatted_old = pd.read_csv("/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb/formatted_customdb.tsv", sep="\t")
formatted_new = formatted_dfv20260213  # 已处理好的 DataFrame
# 2. 确保列顺序一致（保险起见）
formatted_new = formatted_new.reindex(columns=formatted_old.columns)
# 3. 合并两个表
formatted_combined = pd.concat([formatted_old, formatted_new], ignore_index=True)
# 4. 去重（如不想重复记录）
formatted_combined = formatted_combined.drop_duplicates()
formatted_combined

,raw_source_id,raw_target_id,raw_source_type,raw_target_type,relation_type,resource,pmids,key_sentence,source_id,source_type,target_id,target_type,formatted_relation_type
0,ENTREZ:11622,DrugBank:DB00158,Gene,Compound,GNBR::E-::Compound:Gene,CustomDB,NaN,"Furthermore, FA supplementation attenuated the...",DrugBank:DB00158,Compound,ENTREZ:11622,Gene,BioMedGPS::E-::Compound:Gene
1,ENTREZ:11624,DrugBank:DB00158,Gene,Compound,GNBR::E-::Compound:Gene,CustomDB,NaN,"Furthermore, FA supplementation attenuated the...",DrugBank:DB00158,Compound,ENTREZ:11624,Gene,BioMedGPS::E-::Compound:Gene
2,ENTREZ:13076,DrugBank:DB00158,Gene,Compound,GNBR::E-::Compound:Gene,CustomDB,NaN,"Furthermore, FA supplementation attenuated the...",DrugBank:DB00158,Compound,ENTREZ:13076,Gene,BioMedGPS::E-::Compound:Gene
3,ENTREZ:13078,DrugBank:DB00158,Gene,Compound,GNBR::E-::Compound:Gene,CustomDB,NaN,"Furthermore, FA supplementation attenuated the...",DrugBank:DB00158,Compound,ENTREZ:13078,Gene,BioMedGPS::E-::Compound:Gene
4,MONDO:0005404,DrugBank:DB00158,Disease,Compound,GNBR::Pa::Compound:Disease,CustomDB,NaN,Patients with ME/CFS respond positively to ora...,DrugBank:DB00158,Compound,MONDO:0005404,Disease,BioMedGPS::Treatment::Compound:Disease
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19031,ENTREZ:21425,REACT:R-MMU-1632852,Gene,Gene,BioMedGPS::InPathway::Gene:Pathway,CustomDB,NaN,A CRISPR-Cas9-engineered ANXA2E139A mutation i...,ENTREZ:21425,Gene,REACT:R-MMU-1632852,Pathway,BioMedGPS::InPathway::Gene:Pathway
19032,ENTREZ:21425,MONDO:0002771,Gene,Gene,BioMedGPS::Causer::Gene:Disease,CustomDB,NaN,"Notably, we observe lowered TFEB and LC3B leve...",ENTREZ:21425,Gene,MONDO:0002771,Disease,BioMedGPS::Causer::Gene:Disease
19033,MONDO:0002771,ENTREZ:67443,Disease,Disease,BioMedGPS::E-::Disease:Gene,CustomDB,NaN,"Notably, we observe lowered TFEB and LC3B leve...",MONDO:0002771,Disease,ENTREZ:67443,Gene,BioMedGPS::E-::Disease:Gene
19034,REACT:R-MMU-1632852,MONDO:0002771,Pathway,Pathway,BioMedGPS::AssociatedWith::Pathway:Disease,CustomDB,NaN,"Notably, we observe lowered TFEB and LC3B leve...",REACT:R-MMU-1632852,Pathway,MONDO:0002771,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
19035,ENTREZ:12306,MONDO:0002771,Gene,Gene,BioMedGPS::Target::Gene:Disease,CustomDB,NaN,"Collectively, our data demonstrate that ANXA2 ...",ENTREZ:12306,Gene,MONDO:0002771,Disease,BioMedGPS::Target::Gene:Disease

In [9]:
# 5. 写入为新的 formatted_customdb.tsv 文件
formatted_combined.to_csv("/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb/formatted_customdb.tsv", sep="\t", index=False)