## Prepare a full knowledge graph dataset

We need to prepare the training, validation and external test datasets. We will use the training dataset to train the model and the test dataset to evaluate the model for all KGE models.

### [Require to Modify According to Your Situation] Prepare all relation files

We design a strategy to allow users to integrate their expected relation files for different purposes. Such as you might want to include the `malacards_mecfs` dataset when you want to train a model for ME/CFS.

In [1]:
import os

root_dir = os.path.dirname(os.getcwd())

# ---------- Parameters [Must be modified based on your situation] ----------
# dataset_name = "biomedgps-full-v20240127"
dataset_name = "biomedgps"
dataset_version = "v20250731"
skip_rows_not_in_entity_file = True
# The directory names must be consistent with the subdirectories in the formatted_relations folder.
blacklist_databases = []

# It's an optional parameter, if you don't want to split the dataset, you can ignore it.
#split_ratio = 0.8

# Which column will be kept in the final formatted file
relation_type_column = "formatted_relation_type"

# Which file will be used to format the relation types
relation_type_file = "relation_types.tsv"

In [2]:
root_dir

'/Users/zhuzhixing/KG/biomedgps-data'

In [3]:
# ---------- Load data ----------
graph_data_dir = os.path.join(root_dir, "graph_data")
formatted_relation_dir = os.path.join(graph_data_dir, "formatted_relations")

files = []
for dir in os.listdir(formatted_relation_dir):
    dir_path = os.path.join(formatted_relation_dir, dir)
    if os.path.isdir(dir_path):  # 检查是否为目录
        for file in os.listdir(dir_path):
            if file.endswith(".tsv") and file.startswith("formatted_") and dir not in blacklist_databases:
                files.append(os.path.join(dir_path, file))

print("Merging the following files:")
print("\n".join(files))

entity_file = os.path.join(graph_data_dir, "entities.tsv")
print("Number of entities: {}".format(len(open(entity_file).readlines())))

Merging the following files:
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ttd/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/Fibromine/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/dgidb/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/drkg/formatted_drkg.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/biosnap_disease/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/FibROAD/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/monarch/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/cbcg/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ctd/formatted_ctd.tsv
Number of entities: 933231

### Dependencies

In [4]:
import os
import sys

lib_dir = os.path.join(os.path.dirname(os.getcwd()), "lib")

print("Adding {} to sys.path".format(lib_dir))
sys.path.append(lib_dir)

Adding /Users/zhuzhixing/KG/biomedgps-data/lib to sys.path

### Metadata for recording the steps

To save the essential information of all relation files for reproducibility.

In [5]:
from metadata import DatasetMetadata, check_repo_clean

# For getting the correct commit id, we need to check if the repo is clean. If not, you should commit your changes first.
check_repo_clean(file_suffix = ".py", raise_error=False)
repo_commit_id = os.popen("git rev-parse HEAD").read().strip()
repo_path = os.popen("git config --get remote.origin.url").read().strip()
outputdir = os.path.join(root_dir, "datasets", f"{dataset_name}-{dataset_version}-{repo_commit_id[:6]}")
os.makedirs(outputdir, exist_ok=True)

dataset_metadata = DatasetMetadata(
    repo_commit_id=repo_commit_id,
    repo_path=repo_path,
    dataset_name=dataset_name,
    dataset_version=dataset_version,
    data_files=files,
    metadata=None,
)

dataset_metadata.to_json(os.path.join(outputdir, "metadata.json"))

In [6]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   entities/cell-line-ontology/format_clo.py
	modified:   mapping/make_mappings.ipynb
	modified:   prepare_dataset.ipynb
	modified:   relation_types.tsv
	modified:   relations/biosnap/main.ipynb
	modified:   relations/cbcg/formatted_cbcg.tsv
	modified:   relations/cbcg/invalid_formatted_cbcg.tsv
	modified:   relations/cbcg/main.ipynb
	modified:   relations/customdb/customdb_v20240630.tsv
	modified:   relations/customdb/format_customdb.py
	modified:   relations/customdb/formatted_malacards_mecfs.tsv
	modified:   relations/customdb/formatted_merged_all.tsv
	modified:   relations/customdb/main.ipynb
	modified:   relations/dgidb/formatted_dgidb.tsv
	modified:   relations/dgidb/main.ipynb
	modified:   relations/nsides_pending/offsides/main.ipynb
	modified:   relations/nsides_pending/onsides/main.ipynb
	modified:   relations/ttd/drug-disease/main.ipynb
	modified:   relations/ttd/main.ipynb
	modified:   relations/ttd/target-pathway/main.ipynb
	modified:   relations/wikipathways_pending/main.ipynb
	modified:   scripts/extract_entities.sh

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ../graph_analysis/graph_analysis.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	../test_regex.py

In [5]:
! git add .

In [ ]:
git commit -m "data: 202507版-更新多个知识图谱关系文件与脚本

- graph_data/entities/cell-line-ontology/format_clo.py: 修改 Python 脚本
- graph_data/mapping/make_mappings.ipynb: 更新 Jupyter Notebook
- graph_data/prepare_dataset.ipynb: 更新 Jupyter Notebook
- graph_data/relation_types.tsv: 更新 TSV 数据文件，增加了compound和disease，gene等的关系类型，补充了monarch数据库关系类别
- graph_data/relations/biosnap/main.ipynb: 更新 Jupyter Notebook
- graph_data/relations/ctd/: 更新 ctd数据库版本至Jul_2025数据文件
- graph_data/relations/cbcg/formatted_cbcg.tsv: 更新 TSV 数据文件
- graph_data/relations/cbcg/invalid_formatted_cbcg.tsv: 更新 TSV 数据文件
- graph_data/relations/cbcg/main.ipynb: 更新 Jupyter Notebook
- graph_data/relations/customdb/customdb_v20240630.tsv: 手动完成了该版本关系的映射，修改了symptom类别变成phenotype类别
- graph_data/relations/customdb/format_customdb.py: 修改 Python 脚本，补充关系类别
- graph_data/relations/customdb/formatted_malacards_mecfs.tsv: 手动完成了该版本关系的映射，更新 TSV 数据文件
- graph_data/relations/customdb/formatted_merged_all.tsv: 手动完成了该版本关系的映射，更新 TSV 数据文件
- graph_data/relations/customdb/main.ipynb: 更新 Jupyter Notebook
- graph_data/relations/dgidb/formatted_dgidb.tsv: 重新下载了latest版本，更新 TSV 数据文件
- graph_data/relations/dgidb/main.ipynb: 更新 Jupyter Notebook
- graph_data/relations/Monarch/main.ipynb: 更新 Jupyter Notebook，下载最新版本关系数据库，标准化关系类别，增加到202507版本知识图谱中
- graph_data/relations/FibROAD/main.ipynb: 更新 Jupyter Notebook，增加到202507版本知识图谱中
- graph_data/relations/Fibromine/main.ipynb: 更新 Jupyter Noteboo，增加到202507版本知识图谱中
- graph_data/relations/ttd/target-pathway/main.ipynb: 更新 Jupyter Notebook
- graph_data/relations/wikipathways_pending/main.ipynb: 更新 Jupyter Notebook
- graph_data/scripts/extract_entities.sh: 修改 Shell 脚本

### Merge all relation files into one file

In [6]:
import os
import subprocess
import pandas as pd
import tempfile

temp_dir = tempfile.mkdtemp()

args = ["python3", os.path.join(lib_dir, "data.py"), "merge-files"]

for f in files:
    args.extend(["--input", f])

kg_file = os.path.join(temp_dir, "knowledge_graph.tsv")
args.extend(["--output", kg_file])

print("Running: {}".format(" ".join(args)))
args_str = " ".join(args)
!{args_str}

if os.path.exists(kg_file):
    df = pd.read_csv(kg_file, sep="\t")
    source_ids = df[["source_id", "source_type"]].drop_duplicates()
    source_ids.columns = ["id", "label"]
    target_ids = df[["target_id", "target_type"]].drop_duplicates()
    target_ids.columns = ["id", "label"]
    ids = pd.concat([source_ids, target_ids]).drop_duplicates()
    print("Number of unique entity ids: {}".format(len(ids)))
    print("Number of deduplicated relations: {}".format(len(df.drop_duplicates())))

    entities = pd.read_csv(entity_file, sep="\t")

    dataset_metadata.add_step(
        note="Merge all relation files into one file",
        entity_file_before=None,
        entity_file_after=entity_file,
        relation_file_before=None,
        relation_file_after=kg_file,
    )

Running: python3 /Users/zhuzhixing/KG/biomedgps-data/lib/data.py merge-files --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ttd/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/Fibromine/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/dgidb/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/drkg/formatted_drkg.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/biosnap_disease/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/FibROAD/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/monarch/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/cbcg/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ctd/formatted_ctd.tsv --output /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpjr7pn4ye/knowledge_graph.tsv
/Users/zhuzhixing/KG/biomedgps-data/lib/data.py:304: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(file, sep=detect_separator(file)) for file in input]
Merging the following files:  ('/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ttd/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/Fibromine/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/dgidb/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/drkg/formatted_drkg.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/biosnap_disease/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/FibROAD/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/monarch/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/cbcg/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ctd/formatted_ctd.tsv')
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ttd/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 14027
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/Fibromine/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 739
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/dgidb/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 1397
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/drkg/formatted_drkg.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 5464332
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/biosnap_disease/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 87130
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/FibROAD/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 1094
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 2682
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/monarch/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 3046730
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/cbcg/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 431
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ctd/formatted_ctd.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 36160656
The following columns will be used:  ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type']
Number of rows in the merged dataframe:  44779218

/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/ipykernel_78904/3759005214.py:21: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(kg_file, sep="\t")

Number of unique entity ids: 199469
Number of deduplicated relations: 44779218

/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/ipykernel_78904/3759005214.py:30: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  entities = pd.read_csv(entity_file, sep="\t")

### [Optional] Filter out the relations that are not matched with our requirements

We can follow the results generated by the graph_analysis.ipynb to decide which relations should be kept.

In [7]:
# The kg_file variable might have been updated by the following cells, so we put the definition here for avoiding to load the wrong file
kg_file = os.path.join(temp_dir, "knowledge_graph.tsv")

In [8]:
temp_dir

'/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpjr7pn4ye'

In [9]:
df = pd.read_csv(kg_file, sep="\t")
df

/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/ipykernel_78904/1758338738.py:1: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(kg_file, sep="\t")

,raw_source_id,raw_target_id,raw_source_type,raw_target_type,relation_type,resource,pmids,key_sentence,source_id,source_type,target_id,target_type,formatted_relation_type
0,SYMBOL:CCR2,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:729230,Gene,MONDO:0957421,Disease,DRUGBANK::treats::Compound:Disease
1,SYMBOL:F9,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:2158,Gene,MONDO:0957421,Disease,DRUGBANK::treats::Compound:Disease
2,SYMBOL:HPD,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:3242,Gene,MONDO:0957421,Disease,DRUGBANK::treats::Compound:Disease
3,SYMBOL:KRT6A,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:3853,Gene,MONDO:0957421,Disease,DRUGBANK::treats::Compound:Disease
4,SYMBOL:APOH,ICD-11:4A45,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:350,Gene,MONDO:0007140,Disease,DRUGBANK::treats::Compound:Disease
...,...,...,...,...,...,...,...,...,...,...,...,...,...
44779213,OMIM:613485,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0019171,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44779214,OMIM:613677,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013359,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44779215,OMIM:613980,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013513,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44779216,OMIM:614098,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013572,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44779217,OMIM:616973,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0014855,Disease,BioMedGPS::AssociatedWith::Pathway:Disease

In [10]:
print("Number of relations: {}".format(len(df)))
ignore_relation_types = [
    # Virus gene relations are not useful for our use case.
    "bioarx::Coronavirus_ass_host_gene::Disease:Gene",
    "bioarx::Covid2_acc_host_gene::Disease:Gene",
    "bioarx::DrugHumGen::Compound:Gene",
    "bioarx::DrugVirGen::Compound:Gene",
    "bioarx::HumGenHumGen::Gene:Gene",
    "bioarx::VirGenHumGen::Gene:Gene",
    # We don't like associated_with relation type.
    "PrimeKG::associated_with::Disease:Gene",
    "PrimeKG::associated_with::Gene:Disease",
    "PrimeKG::associated_with::Gene:Symptom",
    "PrimeKG::associated_with::Symptom:Gene",
    # We don't like ontology tree
    "PrimeKG::parent-child::Anatomy:Anatomy",
    "PrimeKG::parent-child::BiologicalProcess:BiologicalProcess",
    "PrimeKG::parent-child::CellularComponent:CellularComponent",
    "PrimeKG::parent-child::Disease:Disease",
    "PrimeKG::parent-child::MolecularFunction:MolecularFunction",
    "PrimeKG::parent-child::Pathway:Pathway",
    "PrimeKG::parent-child::Symptom:Symptom",
]

Number of relations: 44779218

In [11]:
ignore_relation_types

['bioarx::Coronavirus_ass_host_gene::Disease:Gene',
 'bioarx::Covid2_acc_host_gene::Disease:Gene',
 'bioarx::DrugHumGen::Compound:Gene',
 'bioarx::DrugVirGen::Compound:Gene',
 'bioarx::HumGenHumGen::Gene:Gene',
 'bioarx::VirGenHumGen::Gene:Gene',
 'PrimeKG::associated_with::Disease:Gene',
 'PrimeKG::associated_with::Gene:Disease',
 'PrimeKG::associated_with::Gene:Symptom',
 'PrimeKG::associated_with::Symptom:Gene',
 'PrimeKG::parent-child::Anatomy:Anatomy',
 'PrimeKG::parent-child::BiologicalProcess:BiologicalProcess',
 'PrimeKG::parent-child::CellularComponent:CellularComponent',
 'PrimeKG::parent-child::Disease:Disease',
 'PrimeKG::parent-child::MolecularFunction:MolecularFunction',
 'PrimeKG::parent-child::Pathway:Pathway',
 'PrimeKG::parent-child::Symptom:Symptom']

In [12]:
df = df[~df["relation_type"].isin(ignore_relation_types)]
print("Number of relations after removed ignore relation_types: {}".format(len(df)))

Number of relations after removed ignore relation_types: 44779130

In [13]:
df

,raw_source_id,raw_target_id,raw_source_type,raw_target_type,relation_type,resource,pmids,key_sentence,source_id,source_type,target_id,target_type,formatted_relation_type
0,ENTREZ:1,MONDO:0002771,Gene,Disease,Hetionet::DdG::Disease:Gene,FIBROMINE,NaN,NaN,MONDO:0002771,Disease,ENTREZ:1,Gene,BioMedGPS::E-::Disease:Gene
1,ENTREZ:100049587,MONDO:0002771,Gene,Disease,Hetionet::DdG::Disease:Gene,FIBROMINE,NaN,NaN,MONDO:0002771,Disease,ENTREZ:100049587,Gene,BioMedGPS::E-::Disease:Gene
2,ENTREZ:10095,MONDO:0002771,Gene,Disease,Hetionet::DuG::Disease:Gene,FIBROMINE,NaN,NaN,MONDO:0002771,Disease,ENTREZ:10095,Gene,BioMedGPS::E+::Disease:Gene
3,ENTREZ:10103,MONDO:0002771,Gene,Disease,Hetionet::DuG::Disease:Gene,FIBROMINE,NaN,NaN,MONDO:0002771,Disease,ENTREZ:10103,Gene,BioMedGPS::E+::Disease:Gene
4,ENTREZ:10111,MONDO:0002771,Gene,Disease,Hetionet::DuG::Disease:Gene,FIBROMINE,NaN,NaN,MONDO:0002771,Disease,ENTREZ:10111,Gene,BioMedGPS::E+::Disease:Gene
...,...,...,...,...,...,...,...,...,...,...,...,...,...
44713548,OMIM:613485,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0019171,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44713549,OMIM:613677,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013359,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44713550,OMIM:613980,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013513,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44713551,OMIM:614098,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013572,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44713552,OMIM:616973,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0014855,Disease,BioMedGPS::AssociatedWith::Pathway:Disease

In [13]:
print("Number of relations after removed unknown relation_types: {}".format(len(df)))
kg_file_ignore_relation_types_filtered = os.path.join(
    temp_dir, "knowledge_graph_ignore_relation_types_filtered.tsv"
)

Number of relations after removed unknown relation_types: 44779130

In [14]:
relation_type_map = pd.read_csv(
    os.path.join(graph_data_dir, "relation_types.tsv"), sep="\t"
)
relation_type_map

,relation_type,raw_description,formatted_relation_type,description,prompt_template,resource,abbr,source_type,target_type,annotation
0,PrimeKG::parent-child::Anatomy:Anatomy,Parent-child relationship between anatomies,BioMedGPS::ParentChild::Anatomy:Anatomy,A hierarchical relationship between two anatom...,Is there a hierarchical relationship between t...,PrimeKG,parent-child,Anatomy,Anatomy,NaN
1,Hetionet::AdG::Anatomy:Gene,Anatomy downregulates the gene,BioMedGPS::E-::Anatomy:Gene,The gene is not significantly expressed in a s...,Is the #Gene# not significantly expressed in t...,Hetionet,AdG,Anatomy,Gene,Anatomy–downregulates–Gene
2,Hetionet::AeG::Anatomy:Gene,Anatomy expresses the gene,BioMedGPS::E::Anatomy:Gene,The gene has a general level of expression in ...,Does the #Gene# exhibit a general level of exp...,Hetionet,AeG,Anatomy,Gene,Anatomy–expresses–Gene
3,Hetionet::AuG::Anatomy:Gene,Anatomy upregulates the gene,BioMedGPS::E+::Anatomy:Gene,The gene is significantly expressed in a speci...,Is the #Gene# significantly expressed in the #...,Hetionet,AuG,Anatomy,Gene,Anatomy–upregulates–Gene
4,PrimeKG::expression_absent::Anatomy:Gene,Anatomy lacks expression of a gene,BioMedGPS::NE::Anatomy:Gene,The gene is not expressed in a specific anatom...,"Is the #Gene# not expressed in the #Anatomy#, ...",PrimeKG,expression_absent,Anatomy,Gene,NaN
...,...,...,...,...,...,...,...,...,...,...
396,biolink::causes::Disease:BiologicalProcess,A disease causes a biological process,BioMedGPS::Promotor::Disease:BiologicalProcess,A disease promotes or increases the activity o...,Does the #Disease# promote the #BiologicalProc...,biolink,causes,Disease,BiologicalProcess,NaN
397,biolink::subclass_of::Phenotype:Disease,A phenotype is considered a specific manifesta...,BioMedGPS::Present::Disease:Phenotype,A symptom that is present and characteristic o...,Is the #Symptom# characteristic and present in...,biolink,subclass_of,Phenotype,Disease,NaN
398,biolink::part_of::Protein:CellularComponent,The protein is structurally part of a larger c...,BioMedGPS::InCC::Gene:CellularComponent,A gene associated with a specific cellular com...,Is the #Gene# associated with the #CellularCom...,biolink,part_of,Protein,CellularComponent,NaN
399,biolink::caused_by::Disease:CellularComponent,The disease arises due to changes in a cellula...,BioMedGPS::Causer::CellularComponent:Disease,A change or dysfunction in a cellular componen...,Does the #CellularComponent# contribute to the...,biolink,caused_by,Disease,CellularComponent,NaN
400,biolink::subclass_of::CellularComponent:Anatomy,A cellular component is viewed as a part of br...,BioMedGPS::ParentChild::CellularComponent:Anatomy,A cellular component is a part of or derived f...,Is there a hierarchical relationship between #...,biolink,subclass_of,CellularComponent,Anatomy,NaN

In [60]:
relation_types = relation_type_map["relation_type"].tolist()
relation_types

['PrimeKG::parent-child::Anatomy:Anatomy',
 'Hetionet::AdG::Anatomy:Gene',
 'Hetionet::AeG::Anatomy:Gene',
 'Hetionet::AuG::Anatomy:Gene',
 'PrimeKG::expression_absent::Anatomy:Gene',
 'PrimeKG::expression_present::Anatomy:Gene',
 'PrimeKG::parent-child::BiologicalProcess:BiologicalProcess',
 'PrimeKG::interacts_with::BiologicalProcess:Gene',
 'PrimeKG::parent-child::CellularComponent:CellularComponent',
 'PrimeKG::interacts_with::CellularComponent:Gene',
 'DRUGBANK::x-atc::Compound:Atc',
 'DRUGBANK::ddi-interactor-in::Compound:Compound',
 'Hetionet::CrC::Compound:Compound',
 'PrimeKG::synergistic_interaction::Compound:Compound',
 'DRUGBANK::treats::Compound:Disease',
 'GNBR::C::Compound:Disease',
 'GNBR::J::Compound:Disease',
 'GNBR::Mp::Compound:Disease',
 'GNBR::Pa::Compound:Disease',
 'GNBR::Pr::Compound:Disease',
 'GNBR::Sa::Compound:Disease',
 'GNBR::T::Compound:Disease',
 'Hetionet::CpD::Compound:Disease',
 'Hetionet::CtD::Compound:Disease',
 'PrimeKG::contraindication::Compound:Disease',
 'PrimeKG::indication::Compound:Disease',
 'PrimeKG::off-label_use::Compound:Disease',
 'CTD::marker/mechanism::Compound:Disease',
 'CTD::therapeutic::Compound:Disease',
 'bioarx::DrugHumGen:Compound:Gene',
 'bioarx::DrugVirGen:Compound:Gene',
 'DRUGBANK::carrier::Compound:Gene',
 'DRUGBANK::enzyme::Compound:Gene',
 'DRUGBANK::target::Compound:Gene',
 'GNBR::A+::Compound:Gene',
 'GNBR::A-::Compound:Gene',
 'GNBR::B::Compound:Gene',
 'GNBR::E+::Compound:Gene',
 'GNBR::E-::Compound:Gene',
 'GNBR::E::Compound:Gene',
 'GNBR::K::Compound:Gene',
 'GNBR::N::Compound:Gene',
 'GNBR::O::Compound:Gene',
 'GNBR::Z::Compound:Gene',
 'Hetionet::CbG::Compound:Gene',
 'Hetionet::CdG::Compound:Gene',
 'Hetionet::CuG::Compound:Gene',
 'INTACT::ASSOCIATION::Compound:Gene',
 'INTACT::DIRECT INTERACTION::Compound:Gene',
 'INTACT::PHYSICAL ASSOCIATION::Compound:Gene',
 'PrimeKG::carrier::Compound:Gene',
 'PrimeKG::enzyme::Compound:Gene',
 'PrimeKG::target::Compound:Gene',
 'PrimeKG::transporter::Compound:Gene',
 'CTD::affects^abundance::Compound:Gene',
 'CTD::affects^activity::Compound:Gene',
 'CTD::affects^binding::Compound:Gene',
 'CTD::affects^chemical synthesis::Compound:Gene',
 'CTD::affects^cotreatment::Compound:Gene',
 'CTD::affects^expression::Compound:Gene',
 'CTD::affects^localization::Compound:Gene',
 'CTD::affects^methylation::Compound:Gene',
 'CTD::affects^oxidation::Compound:Gene',
 'CTD::affects^phosphorylation::Compound:Gene',
 'CTD::affects^reaction::Compound:Gene',
 'CTD::affects^response to substance::Compound:Gene',
 'CTD::affects^secretion::Compound:Gene',
 'CTD::affects^splicing::Compound:Gene',
 'CTD::decreases^abundance::Compound:Gene',
 'CTD::decreases^activity::Compound:Gene',
 'CTD::decreases^expression::Compound:Gene',
 'CTD::decreases^methylation::Compound:Gene',
 'CTD::decreases^phosphorylation::Compound:Gene',
 'CTD::decreases^reaction::Compound:Gene',
 'CTD::decreases^response to substance::Compound:Gene',
 'CTD::decreases^secretion::Compound:Gene',
 'CTD::decreases^transport::Compound:Gene',
 'CTD::increases^abundance::Compound:Gene',
 'CTD::increases^acetylation::Compound:Gene',
 'CTD::increases^activity::Compound:Gene',
 'CTD::increases^carboxylation::Compound:Gene',
 'CTD::increases^chemical synthesis::Compound:Gene',
 'CTD::increases^cleavage::Compound:Gene',
 'CTD::increases^degradation::Compound:Gene',
 'CTD::increases^expression::Compound:Gene',
 'CTD::increases^lipidation::Compound:Gene',
 'CTD::increases^localization::Compound:Gene',
 'CTD::increases^metabolic processing::Compound:Gene',
 'CTD::increases^methylation::Compound:Gene',
 'CTD::increases^mutagenesis::Compound:Gene',
 'CTD::increases^oxidation::Compound:Gene',
 'CTD::increases^phosphorylation::Compound:Gene',
 'CTD::increases^reaction::Compound:Gene',
 'CTD::increases^reduction::Compound:Gene',
 'CTD::increases^response to substance::Compound:Gene',
 'CTD::increases^secretion::Compound:Gene',
 'CTD::increases^splicing::Compound:Gene',
 'CTD::increases^stability::Compound:Gene',
 'CTD::increases^sumoylation::Compound:Gene',
 'CTD::increases^transport::Compound:Gene',
 'CTD::increases^ubiquitination::Compound:Gene',
 'CTD::increases^uptake::Compound:Gene',
 'Hetionet::CcSE::Compound:SideEffect',
 'PrimeKG::side_effect::Compound:Symptom',
 'Hetionet::DlA::Disease:Anatomy',
 'PrimeKG::contraindication::Disease:Compound',
 'PrimeKG::indication::Disease:Compound',
 'PrimeKG::off-label_use::Disease:Compound',
 'Hetionet::DrD::Disease:Disease',
 'PrimeKG::parent-child::Disease:Disease',
 'bioarx::Coronavirus_ass_host_gene::Disease:Gene',
 'bioarx::Covid2_acc_host_gene::Disease:Gene',
 'Hetionet::DaG::Disease:Gene',
 'Hetionet::DdG::Disease:Gene',
 'Hetionet::DuG::Disease:Gene',
 'PrimeKG::associated_with::Disease:Gene',
 'Hetionet::DpS::Disease:Symptom',
 'HSDN::has_symptom::Disease:Symptom',
 'PrimeKG::phenotype_absent::Disease:Symptom',
 'PrimeKG::phenotype_present::Disease:Symptom',
 'PrimeKG::expression_absent::Gene:Anatomy',
 'PrimeKG::expression_present::Gene:Anatomy',
 'Hetionet::GpBP::Gene:BiologicalProcess',
 'PrimeKG::interacts_with::Gene:BiologicalProcess',
 'Hetionet::GpCC::Gene:CellularComponent',
 'PrimeKG::interacts_with::Gene:CellularComponent',
 'DGIDB::ACTIVATOR::Gene:Compound',
 'DGIDB::AGONIST::Gene:Compound',
 'DGIDB::ALLOSTERIC MODULATOR::Gene:Compound',
 'DGIDB::ANTAGONIST::Gene:Compound',
 'DGIDB::ANTIBODY::Gene:Compound',
 'DGIDB::BINDER::Gene:Compound',
 'DGIDB::BLOCKER::Gene:Compound',
 'DGIDB::CHANNEL BLOCKER::Gene:Compound',
 'DGIDB::INHIBITOR::Gene:Compound',
 'DGIDB::MODULATOR::Gene:Compound',
 'DGIDB::OTHER::Gene:Compound',
 'DGIDB::PARTIAL AGONIST::Gene:Compound',
 'DGIDB::POSITIVE ALLOSTERIC MODULATOR::Gene:Compound',
 'PrimeKG::carrier::Gene:Compound',
 'PrimeKG::enzyme::Gene:Compound',
 'PrimeKG::target::Gene:Compound',
 'PrimeKG::transporter::Gene:Compound',
 'GNBR::D::Gene:Disease',
 'GNBR::G::Gene:Disease',
 'GNBR::J::Gene:Disease',
 'GNBR::L::Gene:Disease',
 'GNBR::Md::Gene:Disease',
 'GNBR::Te::Gene:Disease',
 'GNBR::Ud::Gene:Disease',
 'GNBR::U::Gene:Disease',
 'GNBR::X::Gene:Disease',
 'GNBR::Y::Gene:Disease',
 'PrimeKG::associated_with::Gene:Disease',
 'CTD::marker/mechanism::Gene:Disease',
 'CTD::therapeutic::Gene:Disease',
 'bioarx::HumGenHumGen:Gene:Gene',
 'bioarx::VirGenHumGen:Gene:Gene',
 'GNBR::B::Gene:Gene',
 'GNBR::E+::Gene:Gene',
 'GNBR::E::Gene:Gene',
 'GNBR::H::Gene:Gene',
 'GNBR::I::Gene:Gene',
 'GNBR::Q::Gene:Gene',
 'GNBR::Rg::Gene:Gene',
 'GNBR::V+::Gene:Gene',
 'GNBR::W::Gene:Gene',
 'Hetionet::GcG::Gene:Gene',
 'Hetionet::GiG::Gene:Gene',
 'Hetionet::Gr>G::Gene:Gene',
 'INTACT::ADP RIBOSYLATION REACTION::Gene:Gene',
 'INTACT::ASSOCIATION::Gene:Gene',
 'INTACT::CLEAVAGE REACTION::Gene:Gene',
 'INTACT::COLOCALIZATION::Gene:Gene',
 'INTACT::DEPHOSPHORYLATION REACTION::Gene:Gene',
 'INTACT::DIRECT INTERACTION::Gene:Gene',
 'INTACT::PHOSPHORYLATION REACTION::Gene:Gene',
 'INTACT::PHYSICAL ASSOCIATION::Gene:Gene',
 'INTACT::PROTEIN CLEAVAGE::Gene:Gene',
 'INTACT::UBIQUITINATION REACTION::Gene:Gene',
 'STRING::ACTIVATION::Gene:Gene',
 'STRING::BINDING::Gene:Gene',
 'STRING::CATALYSIS::Gene:Gene',
 'STRING::EXPRESSION::Gene:Gene',
 'STRING::INHIBITION::Gene:Gene',
 'STRING::OTHER::Gene:Gene',
 'STRING::PTMOD::Gene:Gene',
 'STRING::REACTION::Gene:Gene',
 'PrimeKG::ppi::Gene:Gene',
 'Hetionet::GpMF::Gene:MolecularFunction',
 'PrimeKG::interacts_with::Gene:MolecularFunction',
 'Hetionet::GpPW::Gene:Pathway',
 'PrimeKG::interacts_with::Gene:Pathway',
 'CTD::InPathway::Gene:Pathway',
 'PrimeKG::associated_with::Gene:Symptom',
 'GNBR::in_tax::Gene:Tax',
 'PrimeKG::interacts_with::MolecularFunction:Gene',
 'PrimeKG::parent-child::MolecularFunction:MolecularFunction',
 'PrimeKG::interacts_with::Pathway:Gene',
 'PrimeKG::parent-child::Pathway:Pathway',
 'Hetionet::PCiC::PharmacologicClass:Compound',
 'PrimeKG::side_effect::Symptom:Compound',
 'PrimeKG::phenotype_absent::Symptom:Disease',
 'PrimeKG::phenotype_present::Symptom:Disease',
 'PrimeKG::associated_with::Symptom:Gene',
 'PrimeKG::parent-child::Symptom:Symptom',
 'CTD::affects^acetylation::Compound:Gene',
 'CTD::increases^alkylation::Compound:Gene',
 'CTD::decreases^metabolic processing::Compound:Gene',
 'CTD::affects^metabolic processing::Compound:Gene',
 'CTD::decreases^acetylation::Compound:Gene',
 'CTD::decreases^amination::Compound:Gene',
 'CTD::decreases^localization::Compound:Gene',
 'CTD::increases^glucuronidation::Compound:Gene',
 'CTD::increases^sulfation::Compound:Gene',
 'CTD::affects^hydrolysis::Compound:Gene',
 'CTD::increases^hydroxylation::Compound:Gene',
 'CTD::affects^transport::Compound:Gene',
 'CTD::increases^O-linked glycosylation::Compound:Gene',
 'CTD::increases^palmitoylation::Compound:Gene',
 'CTD::increases^ADP-ribosylation::Compound:Gene',
 'CTD::increases^glutathionylation::Compound:Gene',
 'CTD::increases^glycosylation::Compound:Gene',
 'CTD::decreases^degradation::Compound:Gene',
 'CTD::decreases^cleavage::Compound:Gene',
 'CTD::affects^cleavage::Compound:Gene',
 'CTD::increases^export::Compound:Gene',
 'CTD::decreases^export::Compound:Gene',
 'CTD::affects^export::Compound:Gene',
 'CTD::decreases^sumoylation::Compound:Gene',
 'CTD::decreases^ADP-ribosylation::Compound:Gene',
 'CTD::decreases^uptake::Compound:Gene',
 'CTD::decreases^stability::Compound:Gene',
 'CTD::increases^import::Compound:Gene',
 'CTD::increases^nitrosation::Compound:Gene',
 'CTD::affects^folding::Compound:Gene',
 'CTD::affects^uptake::Compound:Gene',
 'CTD::decreases^palmitoylation::Compound:Gene',
 'CTD::increases^hydrolysis::Compound:Gene',
 'CTD::decreases^chemical synthesis::Compound:Gene',
 'CTD::decreases^ubiquitination::Compound:Gene',
 'CTD::affects^sumoylation::Compound:Gene',
 'CTD::affects^reduction::Compound:Gene',
 'CTD::affects^acylation::Compound:Gene',
 'CTD::affects^lipidation::Compound:Gene',
 'CTD::increases^prenylation::Compound:Gene',
 'CTD::affects^import::Compound:Gene',
 'CTD::decreases^farnesylation::Compound:Gene',
 'CTD::decreases^hydrolysis::Compound:Gene',
 'CTD::affects^glycosylation::Compound:Gene',
 'CTD::increases^folding::Compound:Gene',
 'CTD::decreases^ethylation::Compound:Gene',
 'CTD::decreases^reduction::Compound:Gene',
 'CTD::decreases^O-linked glycosylation::Compound:Gene',
 'CTD::decreases^folding::Compound:Gene',
 'CTD::decreases^import::Compound:Gene',
 'CTD::increases^acylation::Compound:Gene',
 'CTD::affects^degradation::Compound:Gene',
 'CTD::decreases^oxidation::Compound:Gene',
 'CTD::affects^N-linked glycosylation::Compound:Gene',
 'CTD::affects^alkylation::Compound:Gene',
 'CTD::increases^amination::Compound:Gene',
 'CTD::IS_ASSOCIATED_WITH::Disease:BiologicalProcess',
 'CTD::IS_ASSOCIATED_WITH::Disease:MolecularFunction',
 'CTD::IS_ASSOCIATED_WITH::Disease:CellularComponent',
 'CTD::IS_ASSOCIATED_WITH::Gene:Pathway',
 'CTD::IS_ASSOCIATED_WITH::Compound:Pathway',
 'CTD::IS_ASSOCIATED_WITH::Disease:Pathway',
 'CTD::IS_ASSOCIATED_WITH::Compound:Disease',
 'CTD::IS_ASSOCIATED_WITH::Gene:Disease',
 'CTD::marker/mechanism|therapeutic::Gene:Disease',
 'CTD::increases^glycation::Compound:Gene',
 'CTD::decreases^glycation::Compound:Gene',
 'CTD::increases^carbamoylation::Compound:Gene',
 'CTD::decreases^mutagenesis::Compound:Gene',
 'CTD::increases^N-linked glycosylation::Compound:Gene',
 'CTD::affects^carboxylation::Compound:Gene',
 'CTD::decreases^splicing::Compound:Gene',
 'CTD::affects^glycation::Compound:Gene',
 'CTD::affects^sulfation::Compound:Gene',
 'CTD::decreases^myristoylation::Compound:Gene',
 'CTD::decreases^prenylation::Compound:Gene',
 'CTD::affects^farnesylation::Compound:Gene',
 'CTD::decreases^geranoylation::Compound:Gene',
 'CTD::decreases^N-linked glycosylation::Compound:Gene',
 'CTD::decreases^lipidation::Compound:Gene',
 'CTD::affects^glutathionylation::Compound:Gene',
 'CTD::increases^ribosylation::Compound:Gene',
 'CTD::decreases^acylation::Compound:Gene',
 'CTD::decreases^glucuronidation::Compound:Gene',
 'CTD::affects^polymerization::Compound:Gene',
 'CTD::decreases^nitrosation::Compound:Gene',
 'CTD::decreases^carboxylation::Compound:Gene',
 'CTD::decreases^carbamoylation::Compound:Gene',
 'CTD::affects^mutagenesis::Compound:Gene',
 'CTD::decreases^alkylation::Compound:Gene',
 'CTD::decreases^glutathionylation::Compound:Gene',
 'CTD::decreases^hydroxylation::Compound:Gene',
 'CTD::decreases^sulfation::Compound:Gene',
 'CTD::affects^hydroxylation::Compound:Gene',
 'CTD::affects^glucuronidation::Compound:Gene',
 'CTD::decreases^glycosylation::Compound:Gene',
 'CTD::increases^farnesylation::Compound:Gene',
 'CTD::affects^stability::Compound:Gene',
 'CTD::affects^ubiquitination::Compound:Gene']

In [61]:
df = df[df["relation_type"].isin(relation_types)]

In [62]:
df

,raw_source_id,raw_target_id,raw_source_type,raw_target_type,relation_type,resource,pmids,key_sentence,source_id,source_type,target_id,target_type,formatted_relation_type
0,HGNC:9864,CHEMBL:CHEMBL107430,Gene,Compound,DGIDB::AGONIST::Gene:Compound,DGIDB,NaN,NaN,DrugBank:DB05653,Compound,ENTREZ:5914,Gene,BioMedGPS::Agonist::Compound:Gene
1,HGNC:3467,CHEMBL:CHEMBL1200598,Gene,Compound,DGIDB::AGONIST::Gene:Compound,DGIDB,NaN,NaN,MESH:C004955,Compound,ENTREZ:2099,Gene,BioMedGPS::Agonist::Compound:Gene
2,HGNC:3468,CHEMBL:CHEMBL1200598,Gene,Compound,DGIDB::AGONIST::Gene:Compound,DGIDB,NaN,NaN,MESH:C004955,Compound,ENTREZ:2100,Gene,BioMedGPS::Agonist::Compound:Gene
3,HGNC:9236,CHEMBL:CHEMBL1236924,Gene,Compound,DGIDB::MODULATOR::Gene:Compound,DGIDB,NaN,NaN,DrugBank:DB05490,Compound,ENTREZ:5468,Gene,BioMedGPS::Modulator::Compound:Gene
4,HGNC:9253,CHEMBL:CHEMBL1269597,Gene,Compound,DGIDB::INHIBITOR::Gene:Compound,DGIDB,NaN,NaN,DrugBank:DB12451,Compound,ENTREZ:5478,Gene,BioMedGPS::Inhibitor::Compound:Gene
...,...,...,...,...,...,...,...,...,...,...,...,...,...
41714403,OMIM:613485,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0019171,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
41714404,OMIM:613677,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013359,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
41714405,OMIM:613980,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013513,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
41714406,OMIM:614098,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013572,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
41714407,OMIM:616973,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0014855,Disease,BioMedGPS::AssociatedWith::Pathway:Disease

In [19]:
ignore_formatted_relation_types = [
    # There are too much relations in this relation type, but they might not useful.
    "BioMedGPS::Interaction::Compound:Compound",
    # We don't like associated_with relation type.
    "BioMedGPS::AssociatedWith::Gene:Gene",
]

In [20]:
df = df[~df["formatted_relation_type"].isin(ignore_formatted_relation_types)]
print("Number of relations after removed ignore formatted_relation_types: {}".format(len(df)))

Number of relations after removed ignore formatted_relation_types: 42874555

In [65]:
df

,raw_source_id,raw_target_id,raw_source_type,raw_target_type,relation_type,resource,pmids,key_sentence,source_id,source_type,target_id,target_type,formatted_relation_type
0,HGNC:9864,CHEMBL:CHEMBL107430,Gene,Compound,DGIDB::AGONIST::Gene:Compound,DGIDB,NaN,NaN,DrugBank:DB05653,Compound,ENTREZ:5914,Gene,BioMedGPS::Agonist::Compound:Gene
1,HGNC:3467,CHEMBL:CHEMBL1200598,Gene,Compound,DGIDB::AGONIST::Gene:Compound,DGIDB,NaN,NaN,MESH:C004955,Compound,ENTREZ:2099,Gene,BioMedGPS::Agonist::Compound:Gene
2,HGNC:3468,CHEMBL:CHEMBL1200598,Gene,Compound,DGIDB::AGONIST::Gene:Compound,DGIDB,NaN,NaN,MESH:C004955,Compound,ENTREZ:2100,Gene,BioMedGPS::Agonist::Compound:Gene
3,HGNC:9236,CHEMBL:CHEMBL1236924,Gene,Compound,DGIDB::MODULATOR::Gene:Compound,DGIDB,NaN,NaN,DrugBank:DB05490,Compound,ENTREZ:5468,Gene,BioMedGPS::Modulator::Compound:Gene
4,HGNC:9253,CHEMBL:CHEMBL1269597,Gene,Compound,DGIDB::INHIBITOR::Gene:Compound,DGIDB,NaN,NaN,DrugBank:DB12451,Compound,ENTREZ:5478,Gene,BioMedGPS::Inhibitor::Compound:Gene
...,...,...,...,...,...,...,...,...,...,...,...,...,...
41714403,OMIM:613485,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0019171,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
41714404,OMIM:613677,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013359,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
41714405,OMIM:613980,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013513,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
41714406,OMIM:614098,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013572,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
41714407,OMIM:616973,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0014855,Disease,BioMedGPS::AssociatedWith::Pathway:Disease

In [21]:
df.to_csv(kg_file_ignore_relation_types_filtered, sep="\t", index=False)
kg_file = kg_file_ignore_relation_types_filtered
kg_file

'/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpjr7pn4ye/knowledge_graph_ignore_relation_types_filtered.tsv'

### [Optional] Map all mouse genes to human genes as much as possible

In [68]:
## Number of Mouse / Rat / Human Genes
entities = pd.read_csv(entity_file, sep="\t")
genes = entities[entities["label"] == "Gene"]
mouse_genes = genes[genes["taxid"] == 10090]
rat_genes = genes[genes["taxid"] == 10116]
human_genes = genes[genes["taxid"] == 9606]

/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/ipykernel_36003/3387816344.py:2: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  entities = pd.read_csv(entity_file, sep="\t")

In [69]:
## Number of Mouse / Rat / Human Genes
entities = pd.read_csv(entity_file, sep="\t")
genes = entities[entities["label"] == "Gene"]
mouse_genes = genes[genes["taxid"] == 10090]
rat_genes = genes[genes["taxid"] == 10116]
human_genes = genes[genes["taxid"] == 9606]

print("Number of Entities: ", len(mouse_genes), len(rat_genes), len(human_genes))
knowledge_graph = pd.read_csv(kg_file, sep="\t")
mouse_relations = knowledge_graph[
    knowledge_graph["source_id"].isin(mouse_genes["id"])
    | knowledge_graph["target_id"].isin(mouse_genes["id"])
]

human_relations = knowledge_graph[
    knowledge_graph["source_id"].isin(human_genes["id"])
    | knowledge_graph["target_id"].isin(human_genes["id"])
]

print(f"Number of mouse gene relations: {len(mouse_relations)}, Number of human gene relations: {len(human_relations)}")

human_mouse_gene_mappings = pd.read_csv(
    os.path.join(graph_data_dir, "mapping", "human_mouse_gene_mappings.tsv"), sep="\t"
)
# NOTE: There might be multiple mappings for a single mouse gene, we will use the first mapping for now. such as PTCD1[ENTREZ:26024] and ATP5MF-PTCD1[ENTREZ:100526740] have the same mouse gene mapping. Ptcd1[ENTREZ: 71799]. 
# human_mouse_gene_map["ENTREZ:71799"]
human_mouse_gene_map = dict(
    zip(
        human_mouse_gene_mappings["entrez_id_mouse"],
        human_mouse_gene_mappings["entrez_id_human"],
    )
)

/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/ipykernel_36003/1502980403.py:2: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  entities = pd.read_csv(entity_file, sep="\t")

Number of Entities:  50015 0 43998

/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/ipykernel_36003/1502980403.py:9: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  knowledge_graph = pd.read_csv(kg_file, sep="\t")

Number of mouse gene relations: 1811538, Number of human gene relations: 30019793

In [70]:
human_mouse_gene_mappings

,key,organism_mouse,taxid_mouse,symbol_mouse,entrez_id_mouse,mgi_id_mouse,hgnc_id_mouse,omim_gene_id_mouse,location_mouse,genome_coordinates_mouse,...,symbol_human,entrez_id_human,mgi_id_human,hgnc_id_human,omim_gene_id_human,location_human,genome_coordinates_human,nucleotide_refseq_id_human,protein_refseq_id_human,swiss_prot_id_human
0,47367020,"mouse, laboratory",10090,Banf1,ENTREZ:23825,MGI:1346330,NaN,NaN,Chr19 4.31 cM,Chr19:5414661-5416904(-),...,BANF1,ENTREZ:8815,NaN,HGNC:17397,OMIM:603811,Chr11 q13.1,Chr11:66002079-66004149(+),"NM_003860,NM_001143985","NP_001137457,NP_003851,XP_016874004,XP_054226339",O75531
1,47367021,"mouse, laboratory",10090,Pde9a,ENTREZ:18585,MGI:1277179,NaN,NaN,Chr17 16.23 cM,Chr17:31605184-31695284(+),...,PDE9A,ENTREZ:5152,NaN,HGNC:8795,OMIM:602973,Chr21 q22.3,Chr21:42653621-42775509(+),"NM_001001571,NM_001315533,NM_002606,NM_0010015...","NP_001001567,NP_001001568,NP_001001569,NP_0010...",O76083
2,47367022,"mouse, laboratory",10090,Asrgl1,ENTREZ:66514,MGI:1913764,NaN,NaN,Chr19 6.06 cM,Chr19:9089083-9112930(-),...,ASRGL1,ENTREZ:80150,NaN,HGNC:16448,OMIM:609212,Chr11 q12.3,Chr11:62337448-62401431(+),"NM_001083926,NM_025080","NP_001077395,NP_079356,XP_011543567,XP_0115435...",Q7L266
3,47367023,"mouse, laboratory",10090,Clpb,ENTREZ:20480,MGI:1100517,NaN,NaN,Chr7 54.63 cM,Chr7:101312958-101444667(+),...,CLPB,ENTREZ:81570,NaN,HGNC:30664,OMIM:616254,Chr11 q13.4,Chr11:72285495-72434680(-),"NM_001258394,NM_001258393,NM_001258392,NM_030813","NP_001245321,NP_001245322,NP_001245323,NP_1104...",Q9H078
4,47367024,"mouse, laboratory",10090,Emd,ENTREZ:13726,MGI:108117,NaN,NaN,ChrX 37.92 cM,ChrX:73298293-73305154(+),...,EMD,ENTREZ:2010,NaN,HGNC:3331,OMIM:300384,ChrX q28,ChrX:154379273-154381574(+),NM_000117,"NP_000108,XP_054182625,XP_054182626",P50402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24580,47387708,"mouse, laboratory",10090,Zswim1,ENTREZ:71971,MGI:1919221,NaN,NaN,Chr2 85.27 cM,Chr2:164664933-164668791(+),...,ZSWIM1,ENTREZ:90204,NaN,HGNC:16155,NaN,Chr20 q13.12,Chr20:45880920-45885266(+),NM_080603,"NP_542170,XP_005260667,XP_005260668,XP_0115274...",Q9BR11
24581,47387709,"mouse, laboratory",10090,Zswim3,ENTREZ:67538,MGI:1914788,NaN,NaN,Chr2 85.27 cM,Chr2:164647034-164664047(+),...,ZSWIM3,ENTREZ:140831,NaN,HGNC:16157,OMIM:620336,Chr20 q13.12,Chr20:45857614-45879122(+),NM_080752,NP_542790,Q96MP5
24582,47387710,"mouse, laboratory",10090,Zswim4,ENTREZ:212168,MGI:2443726,NaN,NaN,Chr8 40.59 cM,Chr8:84937571-84963671(-),...,ZSWIM4,ENTREZ:65249,NaN,HGNC:25704,OMIM:620539,Chr19 p13.13-p13.12,Chr19:13795443-13832254(+),"NM_023072,NM_001367834","NP_001354763,NP_075560,XP_016882642,XP_0168826...",Q9H7M6
24583,47387711,"mouse, laboratory",10090,Zswim9,ENTREZ:321008,MGI:2447816,NaN,NaN,Chr7 7.82 cM,Chr7:12992894-13012647(-),...,ZSWIM9,ENTREZ:374920,NaN,HGNC:34495,NaN,Chr19 q13.33,Chr19:48170680-48197620(+),NM_199341,"NP_955373,XP_005259506,XP_006723267,XP_0067232...",Q86XI8
24584,47387712,"mouse, laboratory",10090,Zwint,ENTREZ:52696,MGI:1289227,NaN,NaN,Chr10 37.15 cM,Chr10:72490678-72510796(+),...,ZWINT,ENTREZ:11130,NaN,HGNC:13195,OMIM:609177,Chr10 q21.1,Chr10:56357227-56361273(-),"NM_032997,NM_007057,NM_001005414,NM_001005413","NP_001005413,NP_008988,NP_127490",O95229

In [71]:
graph_data_dir

'/Users/zhuzhixing/KG/biomedgps-data/graph_data'

In [72]:
# We don't like mouse genes, let's convert them to human genes. If a mouse gene doesn't have a human gene mapping, we will keep the mouse gene. So the users can see that the gene is a mouse gene.
# Convert the mouse_genes["id"] Series to a set for faster lookup
mouse_gene_ids = set(mouse_genes["id"].values)

# Vectorized operation for source_id
knowledge_graph["source_id"] = knowledge_graph["source_id"].map(
    lambda x: human_mouse_gene_map.get(x, x) if x in mouse_gene_ids else x
)

# Vectorized operation for target_id
knowledge_graph["target_id"] = knowledge_graph["target_id"].map(
    lambda x: human_mouse_gene_map.get(x, x) if x in mouse_gene_ids else x
)

# Check whether the conversion is successful
converted_mouse_relations = knowledge_graph[
    knowledge_graph["source_id"].isin(mouse_genes["id"])
    | knowledge_graph["target_id"].isin(mouse_genes["id"])
]

converted_human_relations = knowledge_graph[
    knowledge_graph["source_id"].isin(human_genes["id"])
    | knowledge_graph["target_id"].isin(human_genes["id"])
]

# We cannot use the pattern below because some gene names don't follow the pattern. for example, "Bdnf" is used as a human gene in GNBR database.
# pattern = r"^[A-Z][a-z]+$"
# not_matched_genes = knowledge_graph[
#     ((knowledge_graph["source_type"] == "Gene") & knowledge_graph["source_name"].str.match(pattern, na=False)) |
#     ((knowledge_graph["target_type"] == "Gene") & knowledge_graph["target_name"].str.match(pattern, na=False))
# ]
# not_matched_genes[
#     (not_matched_genes["source_id"] == "ENTREZ:627")
#     | (not_matched_genes["target_id"] == "ENTREZ:627")
# ]

converted_not_matched_genes = knowledge_graph[
    knowledge_graph["source_id"].isin(mouse_genes["id"])
    | knowledge_graph["target_id"].isin(mouse_genes["id"])
]

# Expected: 0, xxx
print(
    "Mouse: ",
    len(mouse_relations),
    " Before /",
    len(converted_mouse_relations),
    " After /",
    len(converted_not_matched_genes),
    " Not matched",
)
print(
    "Human: ",
    len(human_relations),
    " Before /",
    len(converted_human_relations),
    " After",
)

Mouse:  1811538  Before / 626946  After / 626946  Not matched
Human:  30019793  Before / 31204171  After

In [73]:
temp_dir

'/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpyrhh8j0k'

In [74]:

# Write the knowledge graph to a file
kg_file_mouse_converted = os.path.join(temp_dir, "knowledge_graph_mouse_converted.tsv")
knowledge_graph.to_csv(kg_file_mouse_converted, sep="\t", index=False)

dataset_metadata.add_step(
    note="Map all mouse genes to human genes as much as possible",
    entity_file_before=entity_file,
    entity_file_after=entity_file,
    relation_file_before=kg_file,
    relation_file_after=kg_file_mouse_converted,
)

kg_file = kg_file_mouse_converted

In [75]:
kg_file

'/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpyrhh8j0k/knowledge_graph_mouse_converted.tsv'

### [Optional] Format all relation types

In [22]:
if relation_type_file and os.path.exists(relation_type_file):
    relation_types = pd.read_csv(relation_type_file, sep="\t")

    print("Number of relation types: {}".format(len(relation_types)))

Number of relation types: 401

In [23]:
 # Read the kg file
knowledge_graph = pd.read_csv(kg_file, sep="\t")

/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/ipykernel_78904/3092633169.py:2: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  knowledge_graph = pd.read_csv(kg_file, sep="\t")

In [24]:
knowledge_graph_origin = knowledge_graph

In [25]:
kg = knowledge_graph_origin[knowledge_graph_origin["relation_type"] == "biolink::expressed_in::Gene:Anatomy"]

# 查看前几行
print(kg.head())

        raw_source_id   raw_target_id raw_source_type raw_target_type  \
6492848    HGNC:10043  UBERON:0000002            Gene         Anatomy
6492849    HGNC:10317  UBERON:0000002            Gene         Anatomy
6492850    HGNC:10441  UBERON:0000002            Gene         Anatomy
6492851    HGNC:11117  UBERON:0000002            Gene         Anatomy
6492852    HGNC:15588  UBERON:0000002            Gene         Anatomy

                               relation_type resource pmids key_sentence  \
6492848  biolink::expressed_in::Gene:Anatomy  biolink   NaN          NaN
6492849  biolink::expressed_in::Gene:Anatomy  biolink   NaN          NaN
6492850  biolink::expressed_in::Gene:Anatomy  biolink   NaN          NaN
6492851  biolink::expressed_in::Gene:Anatomy  biolink   NaN          NaN
6492852  biolink::expressed_in::Gene:Anatomy  biolink   NaN          NaN

              source_id source_type     target_id target_type  \
6492848  UBERON:0000002     Anatomy   ENTREZ:6034        Gene
6492849  UBERON:0000002     Anatomy   ENTREZ:6147        Gene
6492850  UBERON:0000002     Anatomy   ENTREZ:6202        Gene
6492851  UBERON:0000002     Anatomy   ENTREZ:6606        Gene
6492852  UBERON:0000002     Anatomy  ENTREZ:94121        Gene

            formatted_relation_type
6492848  BioMedGPS::E::Anatomy:Gene
6492849  BioMedGPS::E::Anatomy:Gene
6492850  BioMedGPS::E::Anatomy:Gene
6492851  BioMedGPS::E::Anatomy:Gene
6492852  BioMedGPS::E::Anatomy:Gene

In [26]:
knowledge_graph_origin

,raw_source_id,raw_target_id,raw_source_type,raw_target_type,relation_type,resource,pmids,key_sentence,source_id,source_type,target_id,target_type,formatted_relation_type
0,SYMBOL:CCR2,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:729230,Gene,MONDO:0957421,Disease,DRUGBANK::treats::Compound:Disease
1,SYMBOL:F9,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:2158,Gene,MONDO:0957421,Disease,DRUGBANK::treats::Compound:Disease
2,SYMBOL:HPD,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:3242,Gene,MONDO:0957421,Disease,DRUGBANK::treats::Compound:Disease
3,SYMBOL:KRT6A,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:3853,Gene,MONDO:0957421,Disease,DRUGBANK::treats::Compound:Disease
4,SYMBOL:APOH,ICD-11:4A45,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:350,Gene,MONDO:0007140,Disease,DRUGBANK::treats::Compound:Disease
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42874550,OMIM:613485,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0019171,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
42874551,OMIM:613677,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013359,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
42874552,OMIM:613980,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013513,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
42874553,OMIM:614098,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013572,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
42874554,OMIM:616973,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0014855,Disease,BioMedGPS::AssociatedWith::Pathway:Disease

In [27]:
 # Format the relation types
    ## Remove the formatted_relation_type column if it exists
if "formatted_relation_type" in knowledge_graph.columns:
    knowledge_graph = knowledge_graph.drop(columns=["formatted_relation_type"])
    knowledge_graph = knowledge_graph.merge(relation_types[["relation_type", "formatted_relation_type"]], on="relation_type", how="left")
knowledge_graph

,raw_source_id,raw_target_id,raw_source_type,raw_target_type,relation_type,resource,pmids,key_sentence,source_id,source_type,target_id,target_type,formatted_relation_type
0,SYMBOL:CCR2,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:729230,Gene,MONDO:0957421,Disease,BioMedGPS::Treatment::Compound:Disease
1,SYMBOL:F9,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:2158,Gene,MONDO:0957421,Disease,BioMedGPS::Treatment::Compound:Disease
2,SYMBOL:HPD,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:3242,Gene,MONDO:0957421,Disease,BioMedGPS::Treatment::Compound:Disease
3,SYMBOL:KRT6A,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:3853,Gene,MONDO:0957421,Disease,BioMedGPS::Treatment::Compound:Disease
4,SYMBOL:APOH,ICD-11:4A45,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:350,Gene,MONDO:0007140,Disease,BioMedGPS::Treatment::Compound:Disease
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42874550,OMIM:613485,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0019171,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
42874551,OMIM:613677,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013359,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
42874552,OMIM:613980,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013513,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
42874553,OMIM:614098,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013572,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
42874554,OMIM:616973,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0014855,Disease,BioMedGPS::AssociatedWith::Pathway:Disease

In [28]:
invalid_knowledge_graph = knowledge_graph[knowledge_graph["formatted_relation_type"].isna()]
print("Number of invalid knowledge graph: {}".format(len(invalid_knowledge_graph)))

invalid_knowledge_graph_file = os.path.join(temp_dir, "invalid_knowledge_graph.tsv")
invalid_knowledge_graph.to_csv(invalid_knowledge_graph_file, sep="\t", index=False)
print("Please check the invalid knowledge graph file: {}".format(invalid_knowledge_graph_file))

Number of invalid knowledge graph: 87130
Please check the invalid knowledge graph file: /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpjr7pn4ye/invalid_knowledge_graph.tsv

In [29]:
kg_file_relation_types_formatted = os.path.join(temp_dir, "knowledge_graph_relation_types_formatted.tsv")
knowledge_graph.to_csv(kg_file_relation_types_formatted, sep="\t", index=False)

dataset_metadata.add_step(
    note="Format the relation types",
    entity_file_before=entity_file,
    entity_file_after=entity_file,
    relation_file_before=kg_file,
    relation_file_after=kg_file_relation_types_formatted,
)
    
kg_file = kg_file_relation_types_formatted

In [30]:
kg_file

'/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpjr7pn4ye/knowledge_graph_relation_types_formatted.tsv'

### Annotate the knowledge graph with the entities

In [31]:
args = [
    "python3",
    os.path.join(os.path.dirname(lib_dir), "graph_data", "scripts", "annotate_relations.py"),
    "--entity-file",
    entity_file,
    "--relation-file",
    kg_file,
    "--output-dir",
    os.path.dirname(kg_file),
    "--strict-mode" if skip_rows_not_in_entity_file else "",
]

print("Running: {}".format(" ".join(args)))
args_str = " ".join(args)
!{args_str}
annotated_kg_file = os.path.join(temp_dir, "annotated_knowledge_graph.tsv")
print("File written to: {}".format(annotated_kg_file))

dataset_metadata.add_step(
    note="Annotate the knowledge graph with the entities",
    entity_file_before=entity_file,
    entity_file_after=entity_file,
    relation_file_before=kg_file,
    relation_file_after=annotated_kg_file,
)

Running: python3 /Users/zhuzhixing/KG/biomedgps-data/graph_data/scripts/annotate_relations.py --entity-file /Users/zhuzhixing/KG/biomedgps-data/graph_data/entities.tsv --relation-file /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpjr7pn4ye/knowledge_graph_relation_types_formatted.tsv --output-dir /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpjr7pn4ye --strict-mode
Found 42874555 relations in the input file
You're in strict mode, so 0 relations were skipped.
File written to: /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpjr7pn4ye/annotated_knowledge_graph.tsv

### Extract valid entities from the knowledge graph

In [32]:
import pandas as pd

knowledge_graph = pd.read_csv(kg_file, sep="\t", low_memory=False)
entities = pd.read_csv(entity_file, sep="\t", low_memory=False)

source_entities = knowledge_graph[["source_id", "source_type"]].drop_duplicates()
source_entities.columns = ["id", "label"]
target_entities = knowledge_graph[["target_id", "target_type"]].drop_duplicates()
target_entities.columns = ["id", "label"]
source_target_entities = pd.concat([source_entities, target_entities]).drop_duplicates()

valid_entities = pd.merge(source_target_entities, entities, on=["id", "label"], how="left", indicator=True)
knowledge_graph_entities_file = os.path.join(temp_dir, "knowledge_graph_entities.tsv")
valid_entities.to_csv(knowledge_graph_entities_file, sep="\t", index=False)

### Copy all files to the dataset folder

In [33]:
os.makedirs(outputdir, exist_ok=True)

files = [
    (entity_file, os.path.join(outputdir, "annotated_entities.tsv")),
    (kg_file, os.path.join(outputdir, "knowledge_graph.tsv")),
    (annotated_kg_file, os.path.join(outputdir, "annotated_knowledge_graph.tsv")),
    (knowledge_graph_entities_file, os.path.join(outputdir, "knowledge_graph_entities.tsv")),
]

In [34]:
files

[('/Users/zhuzhixing/KG/biomedgps-data/graph_data/entities.tsv',
  '/Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/annotated_entities.tsv'),
 ('/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpjr7pn4ye/knowledge_graph_relation_types_formatted.tsv',
  '/Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/knowledge_graph.tsv'),
 ('/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpjr7pn4ye/annotated_knowledge_graph.tsv',
  '/Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/annotated_knowledge_graph.tsv'),
 ('/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpjr7pn4ye/knowledge_graph_entities.tsv',
  '/Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/knowledge_graph_entities.tsv')]

In [35]:
for f, output_file in files:
    print("Copying {} to {}".format(f, output_file))
    subprocess.check_output(["cp", f, output_file])
    output_zip_file = output_file + ".zip"
    print("Zipping {} to {}".format(output_file, output_zip_file))
    subprocess.check_output(["zip", "-j", output_zip_file, output_file])
    print("Removing {}".format(output_file))
    subprocess.check_output(["rm", output_file])

print("Please found all files in {}".format(outputdir))

Copying /Users/zhuzhixing/KG/biomedgps-data/graph_data/entities.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/annotated_entities.tsv
Zipping /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/annotated_entities.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/annotated_entities.tsv.zip
Removing /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/annotated_entities.tsv
Copying /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpjr7pn4ye/knowledge_graph_relation_types_formatted.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/knowledge_graph.tsv
Zipping /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/knowledge_graph.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/knowledge_graph.tsv.zip
Removing /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/knowledge_graph.tsv
Copying /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpjr7pn4ye/annotated_knowledge_graph.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/annotated_knowledge_graph.tsv
Zipping /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/annotated_knowledge_graph.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/annotated_knowledge_graph.tsv.zip
Removing /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/annotated_knowledge_graph.tsv
Copying /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpjr7pn4ye/knowledge_graph_entities.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/knowledge_graph_entities.tsv
Zipping /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/knowledge_graph_entities.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/knowledge_graph_entities.tsv.zip
Removing /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843/knowledge_graph_entities.tsv
Please found all files in /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250731-0d5843

### Upload the dataset to Dropbox and Dataverse

You can upload the dataset to Dropbox first, then select the files from Dropbox to upload to Dataverse.

https://dataverse.harvard.edu/dataverse/biomedgps